project_id = "gupglbmayvwwxwkunotk"

[functions.send-invitations]
verify_jwt = true

[functions.send-weekly-lunch-reminder]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.validate-invitation]
verify_jwt = false

[functions.webflow-sync]
verify_jwt = true

[functions.get-webflow-token]
verify_jwt = true

[functions.resend-pending-invitations]
verify_jwt = true

[functions.generate-invite-link]
verify_jwt = true

[functions.accept-invitation]
verify_jwt = true

[functions.trigger-reminder-test]
verify_jwt = true
