project_id = "gupglbmayvwwxwkunotk"

[functions.send-invitations]
verify_jwt = true

[functions.send-weekly-lunch-reminder]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.validate-teams-token]
verify_jwt = false

[functions.validate-invitation]
verify_jwt = false

[functions.webflow-sync]
verify_jwt = true

[functions.get-webflow-token]
verify_jwt = true
