CREATE TABLE public.vapid_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_key_jwk jsonb NOT NULL,
  private_key_jwk jsonb NOT NULL,
  application_server_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.vapid_keys ENABLE ROW LEVEL SECURITY;

-- Only service role can access
CREATE POLICY "No direct access" ON public.vapid_keys FOR ALL TO authenticated USING (false);

-- Insert the keys generated by generate-vapid-keys
INSERT INTO public.vapid_keys (public_key_jwk, private_key_jwk, application_server_key) VALUES (
  '{"kty":"EC","crv":"P-256","alg":"ES256","x":"4RjexWGYL9FsVCYPgkxUlwtfUUt-c1K-nXRriwYoBw8","y":"SPHGHkPAfST-fKnnJuKo0p39f6T0KCXnZhJ28G2P0YM","key_ops":["verify"],"ext":true}'::jsonb,
  '{"kty":"EC","crv":"P-256","alg":"ES256","x":"4RjexWGYL9FsVCYPgkxUlwtfUUt-c1K-nXRriwYoBw8","y":"SPHGHkPAfST-fKnnJuKo0p39f6T0KCXnZhJ28G2P0YM","d":"fLWiyo41BmdEePfMgeqeJ5LiFse6aP1rnrJMru8oG54","key_ops":["sign"],"ext":true}'::jsonb,
  'BOEY3sVhmC_RbFQmD4JMVJcLX1FLfnNSvp10a4sGKAcPSPHGHkPAfST-fKnnJuKo0p39f6T0KCXnZhJ28G2P0YM'
);